### ISSUE TITLE
idea: add IUPAC name support via pybacting and OPSIN

### ISSUE THREAD

**Issue by egonw** [sustainable-processes/pura#44]
With [pybacting](https://pypi.org/project/pybacting/) you have access to OPSIN which can convert many IUPAC names to structures:

```python
from pybacting import cdk
from pybacting import opsin

mol = opsin.parseIUPACName("butane")
smiles = cdk.calculateSMILES(mol)
```

**Comment by marcosfelt** [comment]
Thanks for this! We actually already have opsin implemented: https://github.com/sustainable-processes/pura/blob/main/pura/services/opsin.py

We just need better docs

**Comment by marcosfelt** [comment]
Very cool! I'm hesitant to add something with java dependencies. I'd like to keep the number of dependencies to a minimum.

**Comment by egonw** [comment]
Yes, understood. JFTR, pybacting seems to run fine even on Google Colab. It seems that @cthoyt got it to work quite stable. But indeed it adds more MBs to download.
